In [3]:
import pandas as pd
url ="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
df=pd.read_csv(url, names=columns)
#1.معرفة ابعاد مصفوفة البيانات
print("أبعاد مصفوفة البيانات:", df.shape)
#2.عرض انواع البيانات وهل توجد قيم مفقودة
print("\nأنواع البيانات:\n", df.info())
#3.الاحصاءات الوصفية للبيانات
print("\nالإحصاءات الوصفية للبيانات:\n", df.describe())


أبعاد مصفوفة البيانات: (150, 5)
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str    
dtypes: float64(4), str(1)
memory usage: 6.0 KB

أنواع البيانات:
 None

الإحصاءات الوصفية للبيانات:
        sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.

In [5]:
#فحص وجود قيم مفقودة
missing_values = df.isnull().sum()
print("\nعدد القيم المفقودة في كل عمود:\n", missing_values)
#التعويض عن القيم المفقودة باستخدام المتوسط
df['sepal_length'].fillna(df['sepal_length'].mean(), inplace=True) 


عدد القيم المفقودة في كل عمود:
 sepal_length       0
sepal_width        0
petal_length       0
petal_width        0
species            0
species_encoded    0
dtype: int64


C:\Users\Abdulqudos\AppData\Local\Temp\ipykernel_7580\1451283531.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['sepal_length'].fillna(df['sepal_length'].mean(), inplace=True)


0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [4]:
from sklearn.preprocessing import LabelEncoder
#تحويل القيم النصية إلى قيم رقمية
le = LabelEncoder()
df['species_encoded'] = le.fit_transform(df['species'])
print("\nالبيانات بعد تحويل القيم النصية إلى قيم رقمية:\n")
print(df[['species','species_encoded']].drop_duplicates())


البيانات بعد تحويل القيم النصية إلى قيم رقمية:

             species  species_encoded
0        Iris-setosa                0
50   Iris-versicolor                1
100   Iris-virginica                2


In [6]:
#تحتوي على الميزات الحسابية فقط x
x=df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
#تحتوي على المتغير الهدف y
y=df['species_encoded'] 


In [8]:
from sklearn.preprocessing import StandardScaler
#توحيد البيانات 
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

print("\nشكل الميزات بعد التوحيد:\n", x_scaled[:5])  # عرض أول 5 صفوف من البيانات بعد التوحيد



شكل الميزات بعد التوحيد:
 [[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]]


In [9]:
from sklearn.model_selection import train_test_split
# تقسيم البيانات إلى مجموعة التدريب والاختبار   
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)
print(f"\nحجم بيانات التدريب : {x_train.shape}, حجم بيانات الاختبار: {x_test.shape}")



حجم بيانات التدريب : (120, 4), حجم بيانات الاختبار: (30, 4)


In [11]:
from sklearn.ensemble import RandomForestClassifier
#انشاء كائن النموذج
model= RandomForestClassifier(n_estimators=100,random_state=42)
#انشاءالنموذج على بيانات التدريب 
model.fit(x_train,y_train)
print("\nتم تدريب النموذج بنجاح!")


تم تدريب النموذج بنجاح!


In [12]:
#التنبؤ على بيانات الاختبار
y_pred = model.predict(x_test)

print("أول 5 تنبؤات للنموذج:\n", y_pred[:5])
print("أول 5 قيم حقيقية فعلية:\n", y_test.values[:5])


أول 5 تنبؤات للنموذج:
 [1 0 2 1 1]
أول 5 قيم حقيقية فعلية:
 [1 0 2 1 1]


In [13]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# حساب الدقة    
accuracy = accuracy_score(y_test, y_pred)
print(f"(Accuracy)دقة النموذج: {accuracy * 100:.2f}%\n")
 #عرض تقرير التصنيف
print("تقرير التصنيف:\n", classification_report(y_test, y_pred,target_names=le.classes_))
#عرض مصفوفةالارتباك
conf_matrix = confusion_matrix(y_test, y_pred)  
print("مصفوفة الارتباك:\n", conf_matrix)

(Accuracy)دقة النموذج: 100.00%

تقرير التصنيف:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

مصفوفة الارتباك:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
#PyTorch tensors 
x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)

x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

#بناء معمارية الشبكة العصبية
class IrisNeuralNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(IrisNeuralNet,self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)  #  الطبقة الأولى من اليزات المباشرة الى الطبقة الخفية
        self.relu = nn.ReLU()  # تفعيل ReLU للطبقة الأولى
        self.fc2 = nn.Linear(hidden_dim, output_dim) # الطبقة الثانية: من الطبقة الخفية الى الطبقة الاخيرة (طبقة المخرجات)

    def forward(self, x):
        out = self.fc1(x)                # الطبقة الأولى
        out = self.relu(out)             # تفعيل ReLU   
        out = self.fc2(out)               # الطبقة الثانية بدون تفعيل (لأننا سنستخدم CrossEntropyLoss)
        return out
    #تحديد الابعاد (4 ميزات ادخال،16 عقدة خفية، 3 فئات مخرجات)
    import torch.nn as nn
    import torch.optim as optim

    x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
    y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)

    x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
    y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)


    class IrisNeuralNet(nn.Module):
        def __init__(self, input_dim, hidden_dim, output_dim):
            super().__init__()
            self.fc1 = nn.Linear(input_dim, hidden_dim)
            self.relu = nn.ReLU()
            self.fc2 = nn.Linear(hidden_dim, output_dim)

        def forward(self, x):
            x = self.relu(self.fc1(x))
            return self.fc2(x)


    model = IrisNeuralNet(input_dim=4, hidden_dim=16, output_dim=3)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.01)
    #تحديد دالة الخسارة والمُحسّن
    criterion = nn.CrossEntropyLoss()  # دالة الخسارة لتصنيف متعدد   
    optimizer = optim.Adam(model.parameters(), lr=0.01)  # مُحسّن Adam
    #حلقة التدريب
    epochs = 100
    for epoch in range(epochs):
        #التمرير الامامي    
        outputs = model(x_train_tensor)  # تمرير البيانات عبر النموذج
        loss = criterion(outputs, y_train_tensor)  # حساب الخسارة
        #التمرير الخلفي
        optimizer.zero_grad()  # إعادة تعيين التدرجات
        loss.backward()  # حساب التدرجات
        optimizer.step()  # تحديث الأوزان
        if (epoch+1) % 20 == 0:
            print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')
            
    # تقييم النموذج على بيانات الاختبار
    model.eval()  # وضع النموذج في وضع التقييم
    with torch.no_grad():  # تعطيل حساب التدرجات
        predictions = model(x_test_tensor)  # تمرير بيانات الاختبار عبر النموذج
        _, predicted_classes = torch.max(predictions, 1)  # الحصول على الفئة المتوقعة
        correct = (predicted_classes == y_test_tensor).sum().item()  # عدد التنبؤات الصحيحة
        accuracy = correct / y_test_tensor.size(0)  # حساب الدقة
        print(f'Accuracy of the PyTorch model on the test set: {accuracy * 100:.2f}%')
        
    
    

Epoch [20/100], Loss: 0.4654
Epoch [40/100], Loss: 0.2733
Epoch [60/100], Loss: 0.1628
Epoch [80/100], Loss: 0.0984
Epoch [100/100], Loss: 0.0749
Accuracy of the PyTorch model on the test set: 100.00%
